### ISSUE TITLE
Cannot get model for bt-settl

### ISSUE THREAD

**Issue by sylacour** [tomasstolker/species#2]
Hello Tomas

I do not know if it is a bug, or if I did a mistake, but I cannot load the bt-settl models (I did download them using database.add_model("bt-settl").

Here is what I type, and what I got:

>> species.SpeciesInit()
>> model="bt-nextgen"
>> teff=7000
>> read_model = species.ReadModel(model=model,wavel_range=(1., 5.))
>> model_param = {'teff':teff, 'logg':4.0, 'feh':0.0}
>> modelbox = read_model.get_model(model_param=model_param,spec_res=200.)

And here is what I got in return:

Initiating species v0.1.1... [DONE]
Database: /Users/slacour/PycharmProjects/ExoGravity_code/species_database.hdf5
Data folder: /Users/slacour/DATA/SPECIES
Working folder: /Users/slacour/PycharmProjects/ExoGravity_code
Traceback (most recent call last):
  File "/Users/slacour/.conda/envs/ExoGravity_code/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-8ff15ccc18ec>", line 6, in <module>
    modelbox = read_model.get_model(model_param=model_param,spec_res=200.)
  File "/Users/slacour/.conda/envs/ExoGravity_code/lib/python3.7/site-packages/species/read/read_model.py", line 258, in get_model
    flux = self.spectrum_interp(parameters)[0]
  File "/Users/slacour/.conda/envs/ExoGravity_code/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 2489, in __call__
    indices, norm_distances, out_of_bounds = self._find_indices(xi.T)
  File "/Users/slacour/.conda/envs/ExoGravity_code/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 2536, in _find_indices
    norm_distances.append((x - grid[i]) /
IndexError: index -2 is out of bounds for axis 0 with size 0

**Comment by tomasstolker** [comment]
Hi @sylacour, thanks for this first bug report :).

Do you want to use the BT-Setll or BT-NextGen models? It seems that you added BT-Settl but you are trying to read BT-NextGen? From the temperature that you chose (7000 K), you probably want to use the BT-NextGen models?

For BT-NextGen, make sure to set the `teff_range` and to a narrow temperature range when using `add_model`, because this grid is gigantic...

Let me know if this solves the problem! I will do a test in the meanwhile. I am still working on having more diagnostic warnings implemented.

**Comment by tomasstolker** [comment]
To check what the content of the database looks like, you can run:

`database = species.Database()`
`database.list_content()`

And to see which parameters are required for a particular model, e.g.:

`read_model = species.ReadModel('bt-settl')`
`read_model.get_parameters()`

Did you not get an error when adding the BT-Settl models? Because `add_model` probably requires the `spec_res` parameter?

**Comment by tomasstolker** [comment]
After discussing offline, the problem appeared to be related to the `add_model` function. The use was a bit ambiguous so I have added several diagnostic warnings and errors.

Specifically, the DRIFT-PHOENIX and petitCODE models do not require the `wavel_range` and `spec_res` parameters because they are already sampled on a fixed wavelength grid. For the other models, these parameters are required such that the wavelength grid is resampled (with a linear interpolation) when storing the spectra in the database.

For example, for BT-Settl:
`database.add_model(model='bt-settl', wavel_range=(0.5, 10.), spec_res=1000.,  teff_range=(1500., 2000.))`

While for petitCODE-cool-cloudy:
`database.add_model(model='petitcode-cool-cloudy', wavel_range=None, spec_res=None, teff_range=None)`

Or simply:
`database.add_model('petitcode-cool-cloudy')`

These changes were made in commit 23947fc711b2ec120edd2c9f46ae5ec4d6dd95cf and available in the new release (v0.1.3)
