### ISSUE TITLE
spectral_type

### ISSUE THREAD

**Issue by henrikruh** [tomasstolker/species#43]
I dont get any meaningful output from the function CompareSpectra.spectral_type. The issue is apparently solved by transposing the 'spectrum' array in line 146 in empirical.py.

**Comment by tomasstolker** [comment]
Hi @henrikruh,

Thanks for opening this issue. Possibly this is related to a recent update which may not have been fully backward compatible.

I found a small issue in `plot_empirical` though related to bytes vs. strings, which may cause an error depending on your Python version. The issue has been fixed in the Github repo.

Could you pull the latest commits from Github, recreate your *species* database, and rerun `spectral_type`?

Let me know if that solved your problem or provide some details otherwise.
